### ISSUE TITLE
Mixup of column vs row

### ISSUE THREAD

**Issue by BenBE** [nikiroo/jexer#1]
https://github.com/nikiroo/jexer/blob/00ae3f54e495ff26b1e7474b690d28f830e421ce/src/jexer/TTable.java#L194

Should be row in this context.

Also usage of line vs row should be more consistent.

**Comment by nikiroo** [comment]
Yes, "row"... I should have used that term.
(And I did mix up "line" and column in this method, too.)

Will be fixed soon (sadly, it will require changes for any projects using this class).

**Comment by nikiroo** [comment]
Fixed by commit 4413442015934e3eed2e73a90bae3b5a5b9f76e9 "line -> row"
(In ttable and master.)
